name: Build Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Choco help
        uses: crazy-max/ghaction-chocolatey@v2
      - name: Install windows build-tools
        run: choco install visualstudio2017buildtools
      - name: Configure VStudio with npm
        run: npm config set msvs_version 2017
      - name: Install node gyp
        run: npm install --global node-gyp
      - name: Install dependencies
        run: npm ci
      - name: Rebuild dependencies
        run: npm run electron:rebuild
      - name: Configure environment
        run: |
          Set-Content './.env-cmdrc.json' '{ "production": { "NODE_ENV": "production"} }'
          Write-Output "NODE_ENV=production" >> '.env.production'
          Write-Output "SAFE_LINKS=connect-src 'self'" >> '.env.production'
      - name: Build application
        run: npm run make
      - name: Show installer
        run: dir ./out/make/squirrel.windows/x64/



